#pragma kernel Initialize
#pragma kernel ForceCompute
#pragma kernel BoidsCompute

#include "UnityCG.cginc"
#include "../Cginc/Boids.cginc"

[numthreads(1024, 1, 1)]
void Initialize(uint3 id : SV_DispatchThreadID) {
	initialize(id);
}
[numthreads(32, 32, 1)]
void ForceCompute(uint3 id : SV_DispatchThreadID) {
	forceCompute(id);
}
[numthreads(1024, 1, 1)]
void BoidsCompute(uint3 id : SV_DispatchThreadID) {
	boidsCompute(id);
}